### ISSUE TITLE
crash server side

### ISSUE THREAD

**Issue by kdbanman** [polyball/polyball#250] opened 2016-04-21 21:44 UTC
```
[2016-04-21 15:35:07.246] [INFO] [default] - Initializing game
[2016-04-21 15:35:07.246] [INFO] [default] - Number of Players: 0
[2016-04-21 15:35:07.246] [WARN] [default] - Spectator must have dropped after queueing.  Not converting to player.
[2016-04-21 15:35:07.246] [WARN] [default] - Spectator must have dropped after queueing.  Not converting to player.
[2016-04-21 15:35:07.246] [WARN] [default] - Spectator must have dropped after queueing.  Not converting to player.
/cshome/kdbanman/polyball/polyball/shared/model/Arena.js:293
    var goalWidth = this.points[1].x - this.points[0].x;
                                  ^

TypeError: Cannot read property 'x' of undefined
    at new Arena (/cshome/kdbanman/polyball/polyball/shared/model/Arena.js:293:35)
    at addOrResetArena (/cshome/kdbanman/polyball/polyball/shared/Model.js:204:17)
    at initializeGame [as _onTimeout] (/cshome/kdbanman/polyball/polyball/server/Engine.js:69:19)
    at Timer.listOnTimeout (timers.js:92:15)

```

**Comment by ryant26** [comment] 2016-04-28 06:22
Do you have any idea how I could go about replicating this?

**Comment by kdbanman** [comment] 2016-04-28 13:50
I was just rushing to shut down the lab machine and I noticed the server
crashed.  I don't really know what happened.  Maybe I closed a bunch of
tabs really really fast?

**Comment by ryant26** [comment] 2016-05-23 01:07
I cant reproduce this. Closing until we can do so.

**Closed by ryant26** 2016-05-23 01:08 UTC
Labels: bug, ready
